[package]
authors = ["Andre Prado <andreprado88@gmail.com>"]
edition = "2018"
name = "blogpost-statemachine"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "blog"
path = "src/lib.rs"
